numpy array and basic 

In [2]:
import numpy as np 
arr_1d=np.array([1,2,3,4])
print(arr_1d)
print("this is the 2 array")
arr_2d=np.array([[1,2,4],[1,2,3]])
print(arr_2d)

[1 2 3 4]
this is the 2 array
[[1 2 4]
 [1 2 3]]


In [5]:
# MULTIPLICATION IN THE LIST  
list_p=[1,2,3,4,4]
print("multiplication:",list_p*2)
# MULTIPLICATION IN THE NUMPY ARRAY
np_py=np.array([123,424,4])
print(np_py*2)

multiplication: [1, 2, 3, 4, 4, 1, 2, 3, 4, 4]
[246 848   8]


In [17]:
import time 
start=time.time()
play=[i*2 for i in range(1000)]
print(time.time()-start)

0.0008182525634765625


In [16]:
import time 
start=time.time()
np_array=np.arange(10000)*2
print(time.time()-start)    

0.0005028247833251953


In [2]:
import numpy as np
np_array=np.zeros((3,4))
print(np_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
import numpy as np
np_array=np.ones((4,5))
print(np_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
import numpy as np
np_full=np.full((3,4),7)
print(np_full)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [5]:
import numpy as np
np_array=np.array([[1,2,3],[1,2,3]])
print(np_array)
print(np_array.shape)

[[1 2 3]
 [1 2 3]]
(2, 3)


# the vector , matrix and tensor

vector:   #1 d array is consider as veector because its a single line 
       The list is we can call its a vector   
       what i mean to say is numpy
    import numpy as np 
    np_array=np.array([1,2,3])
    these are the vector and have 3 element

In [ ]:
# vector 
import numpy as np
np_array=np.array([1,2,3])# in this as u can see have only the list that total element in the list is the shape (3,) the 3 is the single line quanttity of the array
print(np_array)
print(np_array.shape)

[1 2 3]
(3,)


matrix : so basically its 2 d array number arranged with having rows and columns as the row is each [] and the coloum would be the element in it is the coloum
these are the matrix that written as row and coloumn and have in terms as ([[1,2,3],[2,3,4]])
([[],[]])

In [ ]:
# matric 
import numpy as np
np_array=np.array([[1,2,3],[1,2,3]])
print(np_array)
print(np)

tensor: with n number of array its have n number of dimension mean more than rows and coloumns and wriiten generally 2 or more  matrix  together 

In [12]:
import numpy as np 
np_array=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(np_array)
# print(np_array.shape)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


PROPERTIES OF THE ARRAY :
                        i am listing the important properties of the numpy array
0.shape
1.reshaped
2.Size
3.reveled
4.dimension
5.flattened
6.datatype

In [ ]:
# shape properties:
                # this function used for to know the shape of the array what is that 
                # how many are layers,rows and coloumns are there
import numpy as np
arr=np.array([[1,2,3],[2,3,4]])
print("shape:",arr.shape)

shape: (2, 3)


In [ ]:
# reshape properties: 
                    # this function is used for the reshaping of the array from 1 d to 2 d

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
reshaped=arr.reshape(1,2,3)
print(reshaped)

[[[1 2 3]
  [4 5 6]]]


In [ ]:
# tranpose properties:
import numpy as np
trans=arr.T
print(trans)

[[1 1]
 [2 2]
 [3 3]]


NOW WE DO THE RESIZE AND RESHAPE  OF THE ARRAY :
RESIZE:
In this we change the size of the whole array 
example: so if the main array =arr
then whole arr will be resize 
RESHAPE:
In this we first stored the copy of the array then change the shape we actually dont change the actuall arr just first make a variable where we can store the copy then rehsape

In [ ]:
#RESIZE:
import numpy as np
arr=np.random.randint(1,51,size=(4,5))
# here we actually changing the array size
arr.resize(3,5)
print(arr)

[[37 22 33 31 14]
 [17 32 50 36 25]
 [45  5  9 34 32]]


In [ ]:
#RESHAPED:
import numpy as np 
arr=np.random.randint(1,51,size=(5,4))
arr_reshaped=arr.reshape(2,10)
print(arr_reshaped)

NUMPY ARRAY SLICING 1D, 2D and 3D

1D ARRAY SLICING : little bit different used  (::)


In [ ]:
#  1D ARRAY INDEXING  SLICING 
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:6:2]) # use the : for the slicing 

[2 4 6]


2D ARRAY SLICING: JUST minnor differnce in this is instead for (::) use the (,,)


Numpy array slicing : method for
1:acessing the specific element 
2:acessing all the rows but specific columns
3:accesing a particular rows


In [ ]:
import numpy as np
arr=np.array([[1,23,4],[2,3,4]])
# This is for the specific element acessing 
print(arr[1,2])
#  This is for the specifc columns and every rows 
print(arr[:,1])
#  this is for the for the specific  rows acessing and in the  specific rows all coloumns

print(arr[:,[1,2]]) # used for two coloumn 
print(arr[1])# targeting whole row of [1] place array start  [2,3,4]is the matrix

4
[23  3]
[2 3 4]


SORTING OF ARRAY:
1D AND 2D ARRAY is little bit differernt  
INTEX:
print(np.sort(use the name of the array u wanna sort))

1D ARRAY SORTING:
in this 1d array the sorting is quite simple as compared to 2 d array
INTEX:print(np.sort())

In [3]:
import numpy as np
arr_1D=np.array([1,2334,53,532,5662,673,6433,25])
#This is quite easy 
print("so 1D sorting is simple\n",np.sort(arr_1D))

so 1D sorting is simple
 [   1   25   53  532  673 2334 5662 6433]


2D ARRAY SORTING:
In this everything is same u just have to add the axis
axis=0 used for the sorting of the coloumns [12,3,4,52,42,42,2]
                                            [112,2,3,4,55,667,2]
                                            [1,2,3,4,5,5,6]
                                            NOW AFTER SORTING
                                            [1,2,3,4,5,5,6]
                                            [12,2,3,4,55,11]
axis=1 used for the sorting of the rows[12,3,24,2,1,0] = after sorting[0,1,2,3,12,24] in the all the rows it will become sort


In [5]:
# SORTING :  
# axis=0 : for column by coloumn sorting 
import numpy as np 
arr=np.array([[27,53,50],[23,45,24]])
print("COLOUMN BY COLOUMN",np.sort(arr,axis=0))
#axis=1 for the row sorting 
print("ROW BY ROW SORTING ",np.sort(arr,axis=1))

COLOUMN BY COLOUMN [[23 45 24]
 [27 53 50]]
ROW BY ROW SORTING  [[27 50 53]
 [23 24 45]]


FILTERING NUMBER : selecting the value or filtering values only when the expression  match or true  if the expression is not right filtering the value 

In [9]:
# FILTERING NUMBER 
import numpy as np 
number=np.array([[1,233,31,24],[134,27,17,52]])
filtering_number=number[number%2==0]
print(filtering_number)

[ 24 134  52]


MASK Filtering : this store the expresssion value in it like a variable that are greater then 2 and less than 10


In [ ]:

mask=number>5
print(number)

[[  1 233  31  24]
 [134  27  17  52]]


WHERE : that funciton is used for the asking of that is present
NP.WHERE vs filtering masking

In [ ]:
import numpy as np
number=np.array([1,2,3,5,4,4,324])
indexing=[1,2,3]
arr_2d=number[indexing]
print(arr_2d)
where_item=np.where([number>5])
print(where_item)

[2 3 5]
(array([0]), array([6]))


NP.where(condtion,x ,y)
x used if the condition is true do this
y for false 

In [ ]:
#2d array doing the filtering and np.where and using some acessing
import numpy as np
arr=np.array([[1,2,34,4],[23,4,4,2]])
indexings=[1,2,3] 
print(arr[:,indexings]) # [:,indexing] is thiws for the rows acess
arr2=np.where(arr>10,arr*2,arr)
print(arr2)

[[ 2 34  4]
 [ 4  4  2]]
[[ 1  2 68  4]
 [46  4  4  2]]


ADDITION AND REMOVE :
new_Array=np.append(array_name,element)


CONCATINATION ARRAY: addition of two array
1.(in this compatability is required for the concatenation so the array must be same dimennsion 2d then the adding also 2d.)
2.combined=np.concatenate((arr1,arr2)) in this new array is made and stored the concatenation of array1 and array2 both 

In [ ]:
import numpy as np
arr=np.array([2,3,4,4])
arr2=np.array([23,34,3,4])
combined=np.concatenate((arr,arr2))
print(combined)

[ 2  3  4  4 23 34  3  4]


ADDITION

DONT ADD DIRECTLY BUT CAN STORE THAT IN A NEW ARRAY np.append


In [13]:
import numpy as np
arr=np.array([12,32,43])
arr3=np.append(arr,[6,3])
print(arr3)

[12 32 43  6  3]


ARRAY COMPATIBILITY :
use this function for checking is the shape  are equally compatible or not  just use the .shape 


In [4]:
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.array([1,2,2])
print(a.shape==b.shape)
print(b.shape==c.shape)

True
True


V STACK: use this a vertical stack and use for the vertical that said for the rows 
H STACK: use for the horizontal coloum save only  

In [1]:
import numpy as np
arr=np.array([[1,2,3,4,4],[23,24,2,3,3]])
row_to_be_store=np.array([1,2,3,4,4])
new_store_array=np.vstack((arr,row_to_be_store))
print(new_store_array)


[[ 1  2  3  4  4]
 [23 24  2  3  3]
 [ 1  2  3  4  4]]
